# Generated by Django 6.0.5 on 2026-09-08 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('football', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoringFormula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('config', models.JSONField()),
                ('checksum_sha256', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerSeasonScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('GK', 'Goalkeeper'), ('DEF', 'Defender'), ('MID', 'Midfielder'), ('FWD', 'Attacker'), ('UNKNOWN', 'Unknown')], max_length=10)),
                ('as_of', models.DateTimeField()),
                ('eligible', models.BooleanField()),
                ('minutes', models.PositiveIntegerField()),
                ('appearances', models.PositiveIntegerField()),
                ('performance_score', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('availability_score', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('final_score', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('metric_breakdown', models.JSONField(default=dict)),
                ('coverage_breakdown', models.JSONField(default=dict)),
                ('context_summary', models.JSONField(default=dict)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.player')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.season')),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scoring.scoringformula')),
            ],
            options={
                'indexes': [models.Index(fields=['season', 'formula', 'as_of', 'position'], name='scoring_pla_season__cb782c_idx')],
                'constraints': [models.UniqueConstraint(fields=('season', 'player', 'formula', 'as_of'), name='uniq_player_season_score')],
            },
        ),
    ]
