# Generated by Django 6.0.5 on 2026-09-08 20:16

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20)),
                ('slug', models.SlugField(unique=True)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-starts_on'],
            },
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(max_length=30)),
                ('provider_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField()),
                ('country_code', models.CharField(blank=True, max_length=3, null=True)),
                ('competition_type', models.CharField(choices=[('DOMESTIC_LEAGUE', 'Domestic league'), ('UCL', 'UEFA Champions League')], max_length=30)),
                ('is_tracked', models.BooleanField(default=False)),
                ('base_importance', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=4)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('provider', 'provider_id'), name='uniq_comp_provider_id')],
            },
        ),
        migrations.CreateModel(
            name='CompetitionSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_season_id', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('league_strength_rating', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('league_strength_multiplier', models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=6)),
                ('last_strength_calculated_at', models.DateTimeField(blank=True, null=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.competition')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.season')),
            ],
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(max_length=30)),
                ('provider_id', models.CharField(max_length=100)),
                ('starts_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('LIVE', 'Live'), ('FINISHED', 'Finished'), ('POSTPONED', 'Postponed'), ('CANCELLED', 'Cancelled')], max_length=20)),
                ('stage_name', models.CharField(blank=True, max_length=100, null=True)),
                ('round_name', models.CharField(blank=True, max_length=100, null=True)),
                ('home_score', models.SmallIntegerField(blank=True, null=True)),
                ('away_score', models.SmallIntegerField(blank=True, null=True)),
                ('last_provider_update', models.DateTimeField(blank=True, null=True)),
                ('stats_ingested_at', models.DateTimeField(blank=True, null=True)),
                ('competition_season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.competitionseason')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(max_length=30)),
                ('provider_id', models.CharField(max_length=100)),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('first_name', models.CharField(blank=True, max_length=80, null=True)),
                ('last_name', models.CharField(blank=True, max_length=80, null=True)),
                ('common_name', models.CharField(blank=True, max_length=150, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('nationality_code', models.CharField(blank=True, max_length=3, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('height_cm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('preferred_foot', models.CharField(blank=True, max_length=20, null=True)),
                ('primary_position', models.CharField(choices=[('GK', 'Goalkeeper'), ('DEF', 'Defender'), ('MID', 'Midfielder'), ('FWD', 'Attacker'), ('UNKNOWN', 'Unknown')], db_index=True, default='UNKNOWN', max_length=10)),
                ('detailed_position', models.CharField(blank=True, max_length=60, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('provider', 'provider_id'), name='uniq_player_provider_id')],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(max_length=30)),
                ('provider_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField()),
                ('short_name', models.CharField(blank=True, max_length=50, null=True)),
                ('country_code', models.CharField(blank=True, max_length=3, null=True)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('provider', 'provider_id'), name='uniq_team_provider_id')],
            },
        ),
        migrations.CreateModel(
            name='PlayerTeamSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shirt_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('provider_position_id', models.CharField(blank=True, max_length=100, null=True)),
                ('provider_detailed_position_id', models.CharField(blank=True, max_length=100, null=True)),
                ('started_on', models.DateField(blank=True, null=True)),
                ('ended_on', models.DateField(blank=True, null=True)),
                ('competition_season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='football.competitionseason')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.player')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.team')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerFixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.CharField(choices=[('GK', 'Goalkeeper'), ('DEF', 'Defender'), ('MID', 'Midfielder'), ('FWD', 'Attacker'), ('UNKNOWN', 'Unknown')], max_length=10)),
                ('provider_position_id', models.CharField(blank=True, max_length=100, null=True)),
                ('started', models.BooleanField(default=False)),
                ('minutes', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(130)])),
                ('jersey_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('context_factor', models.DecimalField(blank=True, decimal_places=5, max_digits=7, null=True)),
                ('opponent_elo_before', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('competition_factor', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('league_factor', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.fixture')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.player')),
                ('opponent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opponent_player_fixtures', to='football.team')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player_fixtures', to='football.team')),
            ],
        ),
        migrations.AddField(
            model_name='fixture',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='away_fixtures', to='football.team'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_fixtures', to='football.team'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='winner_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_fixtures', to='football.team'),
        ),
        migrations.CreateModel(
            name='TeamCompetitionSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('competition_season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.competitionseason')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.team')),
            ],
        ),
        migrations.CreateModel(
            name='TeamEloSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_before', models.DecimalField(decimal_places=3, max_digits=8)),
                ('rating_after', models.DecimalField(decimal_places=3, max_digits=8)),
                ('expected_result', models.DecimalField(decimal_places=6, max_digits=8)),
                ('actual_result', models.DecimalField(decimal_places=2, max_digits=3)),
                ('is_home', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.fixture')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.team')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerFixtureMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metric_key', models.CharField(max_length=80)),
                ('value', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('numerator', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('denominator', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('source_type_id', models.CharField(blank=True, max_length=100, null=True)),
                ('player_fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='football.playerfixture')),
            ],
            options={
                'indexes': [models.Index(fields=['player_fixture', 'metric_key'], name='football_pl_player__d2ef17_idx')],
                'constraints': [models.UniqueConstraint(fields=('player_fixture', 'metric_key'), name='uniq_player_fixture_metric')],
            },
        ),
        migrations.AddConstraint(
            model_name='competitionseason',
            constraint=models.UniqueConstraint(fields=('competition', 'season'), name='uniq_comp_season'),
        ),
        migrations.AddIndex(
            model_name='playerfixture',
            index=models.Index(fields=['player', 'fixture'], name='football_pl_player__90e922_idx'),
        ),
        migrations.AddConstraint(
            model_name='playerfixture',
            constraint=models.UniqueConstraint(fields=('fixture', 'player'), name='uniq_fixture_player'),
        ),
        migrations.AddIndex(
            model_name='fixture',
            index=models.Index(fields=['competition_season', 'starts_at'], name='football_fi_competi_785687_idx'),
        ),
        migrations.AddIndex(
            model_name='fixture',
            index=models.Index(fields=['status', 'starts_at'], name='football_fi_status_fc1008_idx'),
        ),
        migrations.AddConstraint(
            model_name='fixture',
            constraint=models.UniqueConstraint(fields=('provider', 'provider_id'), name='uniq_fixture_provider_id'),
        ),
        migrations.AddConstraint(
            model_name='teamcompetitionseason',
            constraint=models.UniqueConstraint(fields=('team', 'competition_season'), name='uniq_team_comp_season'),
        ),
        migrations.AddIndex(
            model_name='teamelosnapshot',
            index=models.Index(fields=['team', 'fixture'], name='football_te_team_id_184098_idx'),
        ),
        migrations.AddConstraint(
            model_name='teamelosnapshot',
            constraint=models.UniqueConstraint(fields=('fixture', 'team'), name='uniq_fixture_team_elo'),
        ),
    ]
