# Generated by Django 6.0.5 on 2026-09-08 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('football', '0001_initial'),
        ('scoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankingSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_at', models.DateTimeField()),
                ('cutoff_at', models.DateTimeField()),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='scoring.scoringformula')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='football.season')),
            ],
        ),
        migrations.CreateModel(
            name='RankingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('GK', 'Goalkeeper'), ('DEF', 'Defender'), ('MID', 'Midfielder'), ('FWD', 'Attacker'), ('UNKNOWN', 'Unknown')], max_length=10)),
                ('rank', models.PositiveSmallIntegerField()),
                ('score', models.DecimalField(decimal_places=4, max_digits=8)),
                ('previous_rank', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('movement', models.SmallIntegerField(blank=True, null=True)),
                ('minutes', models.PositiveIntegerField()),
                ('metric_breakdown', models.JSONField(default=dict)),
                ('context_summary', models.JSONField(default=dict)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ranking_entries', to='football.player')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='football.team')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='rankings.rankingsnapshot')),
            ],
        ),
        migrations.AddConstraint(
            model_name='rankingsnapshot',
            constraint=models.UniqueConstraint(fields=('season', 'formula', 'cutoff_at'), name='uniq_ranking_snapshot'),
        ),
        migrations.AddIndex(
            model_name='rankingentry',
            index=models.Index(fields=['snapshot', 'position', 'rank'], name='rankings_ra_snapsho_7b8e9b_idx'),
        ),
        migrations.AddIndex(
            model_name='rankingentry',
            index=models.Index(fields=['snapshot', 'player'], name='rankings_ra_snapsho_958bea_idx'),
        ),
        migrations.AddConstraint(
            model_name='rankingentry',
            constraint=models.UniqueConstraint(fields=('snapshot', 'position', 'rank'), name='uniq_snapshot_position_rank'),
        ),
        migrations.AddConstraint(
            model_name='rankingentry',
            constraint=models.UniqueConstraint(fields=('snapshot', 'player'), name='uniq_snapshot_player'),
        ),
    ]
