# Generated by Django 6.0.5 on 2026-09-08 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=30)),
                ('sync_key', models.CharField(max_length=150)),
                ('cursor', models.CharField(blank=True, max_length=500, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('provider', 'sync_key'), name='uniq_provider_sync_key')],
            },
        ),
        migrations.CreateModel(
            name='RawProviderPayload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=30)),
                ('resource_type', models.CharField(max_length=50)),
                ('provider_resource_id', models.CharField(max_length=100)),
                ('request_path', models.CharField(max_length=500)),
                ('payload', models.JSONField()),
                ('payload_sha256', models.CharField(max_length=64)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('http_status', models.PositiveSmallIntegerField()),
            ],
            options={
                'indexes': [models.Index(fields=['provider', 'resource_type', 'provider_resource_id'], name='ingestion_r_provide_f12005_idx'), models.Index(fields=['received_at'], name='ingestion_r_receive_86beda_idx')],
            },
        ),
    ]
